# Global Settings
[global]
debug = true
interval = 60

# ThousandEyes Settings
[thousandeyes]
serviceUrl = "https://servicefinder.thousandeyes.com/retrieve-subdomains?domain="
validateUrl = "https://servicefinder.thousandeyes.com/valid-subdomain?subdomain="
agentLabels = ["Servicefinder"]