# Global Settings
[global]
debug = true
interval = 60

# ThousandEyes Settings
[thousandeyes]
user = "dwoellha@thousandeyes.com"
oauthToken = "ce0c19fe-71d1-4f2a-8723-2176db039fbf"
serviceUrl = "https://servicefinder.thousandeyes.com/retrieve-subdomains?domain="
validateUrl = "https://servicefinder.thousandeyes.com/valid-subdomain?subdomain="
domain = ""
agentLabels = ["Servicefinder"]