name: teFinder

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

env:
  VERSION: v0.2
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        check-latest: true

    - name: Install dependencies
      run: go get .

    - name: Run ID
      run: echo "$VERSION"

    - name: Build exectuable
      run: go build -o teFinder-${{ env.VERSION }} main.go

    - name: Build exectuable for latest Tag
      run: go build -o teFinder-latest main.go

    - name: Upload Executable as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: teFinder-artifact
        path: teFinder-${{ env.VERSION }}
    
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        files: teFinder-${{ env.VERSION }}
        tag_name: "${{ env.VERSION }}"
    
    - name: Release Latest
      uses: softprops/action-gh-release@v1
      with:
        prerelease: false
        files: teFinder-latest
        tag_name: "latest"
